### PR TITLE
kernelci: runtime: lava: add method for retrieving device ID

### PR DESCRIPTION
**Pull request by a-wai**
It can be useful to know the exact device on which a job ran, without having to open the LAVA job page. Ensure this is possible by adding a new `get_device_id()` method to the `Callback` class.

### CODE REVIEW

**Review by JenySadadia — CHANGES_REQUESTED** [review]
Breaking on staging:
```
27/04/2024
21:57:43
  File "/home/kernelci/pipeline/lava_callback.py", line 84, in async_job_submit
27/04/2024
21:57:43
    device_id = job_callback.get_device_id()
27/04/2024
21:57:43
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
27/04/2024
21:57:43
AttributeError: 'Callback' object has no attribute 'get_device_id'
```
Please add `get_device_id` method to parent class constructor i.e. `Runtime`.

**Comment by a-wai** [comment]
Moved code around to avoid possible merge conflicts with #2456

**Comment by a-wai** [comment]
Rebased and added `get_data()` so we can save/inspect the raw callback data for debugging.

**Comment by a-wai** [comment]
Tested on staging: https://staging.kernelci.org:9000/viewer?node_id=6630a4ab4d69e2d7c07dc6ba#line=24
